### ISSUE TITLE
Unknown compiler version, upgrade core_io?

### ISSUE THREAD

**Issue by parasyte** [jethrogb/rust-core_io#14]
I get this panic with `rustc 1.33.0-nightly (93c2f055b 2018-12-15)` cf. https://github.com/jethrogb/rust-core_io/blob/e32e97c925cff4222ed0042d9c13c17d8e7baac2/build.rs#L48

And I cannot build on macOS 😐

```
$ echo 93c2f055ba443385b7c97b1b81fb179db5c9e065 | GIT_DIR=../rust/.git ./build-src.sh
find: -printf: unknown primary or operator
./build-src.sh: line 65: tac: command not found
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```

Patching the bash scripts, I was able to get a build working for `93c2f055b`, but I can't really get patches made for the last 9 months of nightlies. [commit-db.rb](https://github.com/jethrogb/rustc-commit-db) only gives me commit hashes up to December 2016?

**Comment by jethrogb** [comment]
I see the issue with `commit-db.rb`, you need to run it with `--force` for now...

**Comment by jethrogb** [comment]
Also, the dist index has not been updated since November 8 for some reason. I'm trying to figure out if the information can be gotten somewhere else...

**Comment by jethrogb** [comment]
I fixed commit-db and pushed the database changes until today, try it now.

**Comment by jethrogb** [comment]
Inability to build on MacOS was also reported in #13. Unfortunately, I don't have a access to a Mac to test on. I'll gladly accept your PR for MacOS support though!

**Comment by parasyte** [comment]
Sure! I’ll see what I can do about portability in the shell scripts. It will probably come down to conditional execution on `uname` ...
