### ISSUE TITLE
New release to crates.io?

### ISSUE THREAD

**Issue by MathiasKoch** [jethrogb/rust-core_io#27]
Hi guys.

Could you maybe make a new release to crates.io, with the recent closed PRs?

**Comment by MathiasKoch** [comment]
@parasyte @roblabla @jethrogb

**Comment by parasyte** [comment]
I can create a new set of patches for the latest nightly, if that will help...

**Comment by jethrogb** [comment]
Updated to today's nightly and published, sorry for the delay.
