### ISSUE TITLE
Cursor should be available even without collections

### ISSUE THREAD

**Issue by whitequark** [jethrogb/rust-core_io#4]
I think cfg-ing out the impl for Vec makes more sense than just disabling it outright.

**Comment by jethrogb** [comment]
Agreed

**Comment by whitequark** [comment]
Any pointers for implementing that? I'm not sure how to do it without manually editing tons of patches.

**Comment by jethrogb** [comment]
Yeah unfortunately that's the way to go. Even worse, you'll need to amend every single existing commit patching one directory at a time (and rebasing) to keep the patchsets contained. This is necessary to make future patching of non-patched versions easier. I'm open to suggestions improving this scheme, but I don't want the build script to have to depend on `git` or `patch` or so.

**Comment by whitequark** [comment]
> Even worse, you'll need to amend every single existing commit patching one directory at a time (and rebasing) to keep the patchsets contained

Well okay I'm not going to do that...

**Comment by jethrogb** [comment]
I refactored everything so that the git repository only holds patches instead of patched versions. It should now be fairly easy to write a script that lets you modify every patch.

**Comment by whitequark** [comment]
Thanks; I'll look into this when upstreaming our local changes. (For now I had to do a fork of std::io myself.)

**Comment by whitequark** [comment]
So I'm looking into it and to test this change properly, I would have to:
- manually edit twenty nine patches
- pull and build twenty nine rustc's

Building a rustc takes ~a hour on my machine. I'm really not ready to commit to _over 24 hours of non-stop compilation_ just to contribute to this library...

**Comment by whitequark** [comment]
To elaborate: it's not enough to just add `#[cfg]`s because of this part:

```
impl<T> Read for Cursor<T> where T: AsRef<[u8]> {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let n = Read::read(&mut self.fill_buf()?, buf)?;
        self.pos += n as u64;
        Ok(n)
    }
}
```

**Comment by whitequark** [comment]
See #5.

**Comment by jethrogb** [comment]
I added the edit-patches.sh script which made making this change (and should make making future changes) relatively easy.

You of course don't need to actually build old rust nightlies to test this. You can just use rustup to install whatever version you want. I generally start by running nightly-2016-03-11 and switch to a newer one once I start getting compiler errors.
